# Generated by Django 5.0.2 on 2024-02-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6, null=True),
        ),
    ]
